<a href="https://colab.research.google.com/github/YasuharuSuzuki/26_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🐼 Section 12 pandas
# 01_DataFrameの読み込み
pandasを使ってExcelやCSVといった表データを読み込みましょう。

### 📊 pandasについて
<img src="https://pandas.pydata.org/static/img/pandas.svg">

- pandasは、Pythonで使用できるオープンソースのデータ分析ライブラリです。その名前は「PANel DAta」の略で、パネルデータ（行と列で区切られた表形式のデータや、時系列データなど）を扱うのに優れています。
- この後の授業で機械学習を学びますが、機械学習を学ぶ時にはpandasを用いることが一般的です。

### 🎖️ pandasを使うメリット
- 便利なDataFrame、Series: DataFrame,Seriesオブジェクトは、表計算ソフトのようにデータを表形式で扱うことができる機能で、とても便利です。
- 多用なデータ形式のサポート: CSV, Excel, SQL データベース, JSON など様々な形式のデータを利用でき、それらを統一的に扱うことが可能です。
- データ分析機能: グループ化、集計、結合などの操作が簡単に行えます。また、時系列データの分析に特化した機能もあります。
- データクリーニング: 欠損値や重複データの処理が簡単にできます。また、データの型変換や正規化を容易に行うことが可能です。
- パフォーマンス: 内部の演算にはnumpyが使用されており、numpyはC言語で書かれているため、大量の数値データに対して一気に高速な計算を行うことが可能です。
- 可視化: matplotlibやseabornなどの可視化ライブラリとシームレスに連携できます。
- 機械学習ライブラリとの相性の良さ: scikit-learnなどの機械学習ライブラリとスムーズに連携できます。

### 🔰 はじめてみよう
- 今回の講義では、このpandasを使ったデータ分析の基本について学んでいきましょう。

---

### 🌐 参考サイト
#### [【Python入門】7-1. pandasライブラリ](https://utokyo-ipp.github.io/7/7-1.html)

---

### 📑 使用するデータセットについて
#### 🍷 Wineデータセット
- scikit-learnで有名なWineのデータセットには簡単な分類用の「wine dataset」とややデータ量の多い「wine quality dataset」があります。
- 今回はデータ量が少ない「wine dataset」を使用します。
- イタリアのある地域で栽培された３種類のワインについて化学分析を行った結果を特徴量として格納されています。

##### 📈 カラム名と内容
| No. | カラム名 | 内容 |
| --- | --- | --- |
| 1 | alcohol | アルコール度数 | 
| 2 | malic_acid | リンゴ酸 | 
| 3 | ash | 灰分（かいぶん） | 
| 4 | alcalinity_of_ash | 灰分のアルカリ度 | 
| 5 | magnesium | マグネシウム | 
| 6 | total_phenols | 全フェノール含量 | 
| 7 | flavanoids | フラボノイド | 
| 8 | nonflavanoid_phenols | 非フラボノイドフェノール | 
| 9 | proanthocyanins | プロアントシアニン | 
| 10 | color_intensity | 色の濃さ | 
| 11 | hue | 色相 | 
| 12 | od280/od315_of_diluted_wines | 希釈ワイン溶液のOD280／OD315（＝280nmと315nmの吸光度の比） | 
| 13 | proline | プロリン | 
| 14 | target | ワインの品種。目的変数 |

### ⬇️ ライブラリのインストール

In [ ]:
# matplotlib日本語対応ライブラリのインストール
!pip install matplotlib-fontja

### 📁 GoogleDrive の Mount

In [ ]:
# drive.mount()を使用してGoogleDriveをMount
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# os.chdir()を使用してカレントディレクトリを変更。作成したショーットカット名を使ってパスを指定します。
import os
os.chdir('/content/drive/MyDrive/＜作成したショートカット名＞')

### ➜] ライブラリのimport

In [1]:
import pandas as pd # pandasモジュールを読み込む（データ分析ライブラリ）
import numpy as np # NumPyモジュールを読み込む（数値演算ライブラリ）
import matplotlib.pyplot as plt # matplotlib.pyplot モジュールを読み込む（可視化ライブラリ。細かいカスタマイズが可能）
import seaborn as sns # Seabornモジュールを読み込む（可視化ライブラリ。pairplotなど多くのデータ分析情報をplotするのに向いている）

### ✍️ 定数の定義
- データファイルパスを定義しておきます
- データ読み込みの際にご使用してください

In [2]:
# データファイルパス定義
WINE_CSV = "./data/wine.csv"
WINE_XLSX = "./data/wine.xlsx" # データはCSVと同じ
IRIS_CSV = "./data/iris.csv"
IRIS_XLSX = "./data/iris.xlsx" # データはCSVと同じ

## 📚 サンプルプログラム1　CSVからDataFrameを読み込む
- read_csv を使ってCSVデータを読み込みます
- [参考サイト：read_csv()](https://note.nkmk.me/python-pandas-read-csv-tsv/)

In [3]:
# ワインのデータセットを読み込み(CSV)
df_wine_csv = pd.read_csv(WINE_CSV, index_col=None) # indexに使用するカラムが無いため、index_col=Noneを指定します
print("type=" + str(type(df_wine_csv)))
df_wine_csv

type=<class 'pandas.DataFrame'>

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

## 🔰　練習プログラム1　CSVからDataFrameを読み込む(5点)

- あやめのデータセット（IRIS_CSV）をCSVからDataFrameとして読み込んでみましょう  

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# あやめのデータセットを読み込み(CSV)

type=<class 'pandas.DataFrame'>

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#@title 送信処理用共通プログラム（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown 解答の送信に必要です。（中身は絶対に修正しないでください）

import os
os.makedirs(".client/python", exist_ok=True)  # 隠しフォルダを作成
!wget -q https://raw.githubusercontent.com/YasuharuSuzuki/26_programing2/main/91_notebook_client/src/setup.sh -O .client/setup.sh   # 外部コードをダウンロードして隠しフォルダに配置
!chmod +x ./.client/setup.sh
!bash ./.client/setup.sh # 実行

# モジュールの初期化
exec(open('.client/client_setup.py').read())

# ノートブック固有の設定
NOTEBOOK_PATH = "12_pandas/01_DataFrameの読み込み.ipynb"
set_notebook_config(NOTEBOOK_PATH)

In [ ]:
#@title 問1 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=1, button_name="練習プログラム"))

---
---
---

## 📚 サンプルプログラム2　ExcelからDataFrameを読み込む
- read_excel を使ってExcelデータを読み込みます
- [参考サイト：read_excel()](https://note.nkmk.me/python-pandas-read-excel/)
- read_excelには読み込むワークシートを指定する機能などが追加されていますが、基本的にはread_csvと同じ機能を持っています。

In [5]:
# ワインのデータセットを読み込み(XLSX)
df_wine_xlsx = pd.read_excel(WINE_XLSX, index_col=None) # indexに使用するカラムが無いため、index_col=Noneを指定します
print("type=" + str(type(df_wine_xlsx)))
df_wine_xlsx

type=<class 'pandas.DataFrame'>

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,3

- CSVもExcelも同じデータのため、結果は同じです
- 読み込んだDataFrameをコードセルの最後に記述すると、内容を表示できます

## 🔰　練習プログラム2　ExcelからDataFrameを読み込む(5点)

- あやめのデータセット（IRIS_XLSX）をExcelからDataFrameとして読み込んでみましょう  

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# あやめのデータセットを読み込み(XLSX)

type=<class 'pandas.DataFrame'>

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
#@title 問2 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=2, button_name="練習プログラム"))

---
---
---
---
---

## ✔　サンプルプログラム3　データの確認

#### head() / tail()
- head() --- データを先頭から何行か表示できます
- tail() --- データを終端から何行か表示できます

In [7]:
# head() を使って先頭のデータを表示します
# 引数に何も指定しない場合、5行表示されます。
df_wine = df_wine_csv
df_wine.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [8]:
# 引数に行数を指定することも可能です。
df_wine.head(1)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.8,3.06,0.28,2.29,5.64,1.04,3.92,1065,1

In [9]:
# tail() を使って終端のデータを表示します
df_wine.tail()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.7,0.64,1.74,740,3
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.3,0.70,1.56,750,3
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.2,0.59,1.56,835,3
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.3,0.60,1.62,840,3
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.2,0.61,1.60,560,3

In [10]:
# tail()もhead()同様に、行数を指定できます。
df_wine.head(3)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1

#### len() / shape / columns / index / info()
- len() --- 行数を取得
- shape --- 行数、列数を取得
- columns --- 列名（カラム名）を取得
- index --- インデックスを取得
- info() --- 行数、列数、データ型などを表示

In [11]:
# 行数を取得
len(df_wine)

178

In [12]:
# 行数、列数を取得
df_wine.shape

(178, 14)

In [13]:
# 列名（カラム名）を取得
df_wine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='str')

In [14]:
# インデックスを取得
df_wine.index

RangeIndex(start=0, stop=178, step=1)

In [15]:
# データ型の表示
df_wine.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    int64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    int64
 13  target                        178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

## ☑️ 練習プログラム3　データの確認(20点)
- あやめのデータを確認してみましょう
  - head()を使ってみましょう。
  - tail()を使ってみましょう。
  - len()を使ってみましょう。
  - shapeを使ってみましょう。
  - columnsを使ってみましょう。
  - indexを使ってみましょう。
  - info()を使ってみましょう。

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# head() を使って先頭のデータを表示します

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa

In [ ]:
# tail() を使って終端のデータを表示します

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

In [ ]:
# 行数を取得

150

In [19]:
# 行数、列数を取得

In [20]:
# 列名（カラム名）を取得

In [ ]:
# インデックスを取得

RangeIndex(start=1, stop=151, step=1, name='Id')

In [ ]:
# データ型の表示

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [ ]:
#@title 問3 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=3, button_name="練習プログラム"))