<a href="https://colab.research.google.com/github/YasuharuSuzuki/26_programing2/blob/main/" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🐼 Section 12 pandas
# 02_データの抽出と統計操作

---

### 🌐 参考サイト
#### [【Python入門】7-1. pandasライブラリ](https://utokyo-ipp.github.io/7/7-1.html)

---

### ⬇️ ライブラリのインストール

In [ ]:
# matplotlib日本語対応ライブラリのインストール
!pip install matplotlib-fontja

### 📁 GoogleDrive の Mount

In [ ]:
# drive.mount()を使用してGoogleDriveをMount
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# os.chdir()を使用してカレントディレクトリを変更。作成したショーットカット名を使ってパスを指定します。
import os
os.chdir('/content/drive/MyDrive/＜作成したショートカット名＞')

### ➜] ライブラリのimport

In [1]:
import pandas as pd # pandasモジュールを読み込む（データ分析ライブラリ）
import numpy as np # NumPyモジュールを読み込む（数値演算ライブラリ）
import matplotlib.pyplot as plt # matplotlib.pyplot モジュールを読み込む（可視化ライブラリ。細かいカスタマイズが可能）
import seaborn as sns # Seabornモジュールを読み込む（可視化ライブラリ。pairplotなど多くのデータ分析情報をplotするのに向いている）

### ✍️ 定数の定義
- データファイルパスを定義しておきます
- データ読み込みの際にご使用してください

In [2]:
# データファイルパス定義
WINE_CSV = "./data/wine.csv"
WINE_XLSX = "./data/wine.xlsx" # データはCSVと同じ
IRIS_CSV = "./data/iris.csv"
IRIS_XLSX = "./data/iris.xlsx" # データはCSVと同じ

---
---
---
---
---

## 🧑🏻‍🏭　サンプルプログラム4　抽出
### [列名] を使ったSeriesの抽出
- Seriesは１行、１列といった一次元の情報を便利に扱うことができます。
- DataFrameが複数行、複数列を扱えるのに対して、Seriesでは個々の列データを集計するのに便利です。

In [3]:
# ワインのデータセットを読み込み(CSV)
df_wine = pd.read_csv(WINE_CSV, index_col=None) # indexに使用するカラムが無いため、index_col=Noneを指定します

# [列名] を使って、alcoholカラムの先頭5行を表示
df_wine["alcohol"].head()

0    14.23
1    13.20
2    13.16
3    14.37
4    13.24
Name: alcohol, dtype: float64

### .列名 を使ったSeriesの抽出
- . (ドット) を使用してSeriesを抽出することもできます。

In [4]:
# .列名 を使って、alcoholカラムの先頭5行を表示
df_wine.alcohol.head()

0    14.23
1    13.20
2    13.16
3    14.37
4    13.24
Name: alcohol, dtype: float64

### [[列名]] を使ったDataFrameの抽出
- DataFrameとして一部の複数列を抽出することも出来ます

In [5]:
# [[列名]] を使って、total_phenolsとhueの先頭5行を表示
df_wine[["total_phenols","hue"]].head()

   total_phenols   hue
0           2.80  1.04
1           2.65  1.05
2           2.80  1.03
3           3.85  0.86
4           2.80  1.04

### loc[行,列] を使った抽出
- 特定の行、列を抽出することが出来ます
- 各行、各列の指定には[start:stop]を指定してスライスすることも可能です
  - ただし、locを使用した抽出では、stopの値も含まれることに注意してください

In [6]:
# loc[行,列] を使って、データの範囲・位置を指定して複数の値を抽出
df_wine.loc[:5, ['total_phenols','hue']]

   total_phenols   hue
0           2.80  1.04
1           2.65  1.05
2           2.80  1.03
3           3.85  0.86
4           2.80  1.04
5           3.27  1.05

- stopの値も含まれる

### iloc[行番号,列番号] を使った抽出
- ilocを使用すると特定の行、列を番号で抽出することが出来ます。locの番号指定バージョンです。
- 各行、各列の指定には[start:stop]を指定してスライスすることも可能です
  - ilocを使用した抽出では、stopの値は含まれません。listやtupleと同じ挙動をします。
- locと比較すると生の数値を入力することで可読性が下がります。
  - 反面、番号で位置を指定したいときには使いやすい機能です。
  - また、通常あまり気にならない差ではありますが、locよりも高速です。

In [7]:
# iloc[行番号,列番号] を使って、データの範囲・位置を番号で指定して複数の値を抽出
df_wine.iloc[:5, 5:11]

,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue
0,2.80,3.06,0.28,2.29,5.64,1.04
1,2.65,2.76,0.26,1.28,4.38,1.05
2,2.80,3.24,0.30,2.81,5.68,1.03
3,3.85,3.49,0.24,2.18,7.80,0.86
4,2.80,2.69,0.39,1.82,4.32,1.04

- stopの値は含まれない

### [条件式]による抽出
- 特定の行を選択することが出来ます

In [8]:
# 条件抽出: hueカラムの値が0.80未満の行を抽出して先頭5行を表示
df_wine[df_wine.hue < 0.80].head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
84,11.84,0.89,2.58,18.0,94,2.20,2.21,0.22,2.35,3.05,0.79,3.08,520,2
110,11.46,3.74,1.82,19.5,107,3.18,2.58,0.24,3.58,2.90,0.75,2.81,562,2
118,12.77,3.43,1.98,16.0,80,1.63,1.25,0.43,0.83,3.40,0.70,2.12,372,2
123,13.05,5.80,2.13,21.5,86,2.62,2.65,0.30,2.01,2.60,0.73,3.10,380,2
124,11.87,4.31,2.39,21.0,82,2.86,3.03,0.21,2.91,2.80,0.75,3.64,380,2

## 🕵️‍♂️ 練習プログラム4　抽出(15点)
- あやめのデータセットについて各種抽出を行ってみましょう
  - [列名] を使ったSeriesの抽出
  - .列名 を使ったSeriesの抽出
  - [[列名,列名]] を使ったDataFrameの抽出
  - loc を使った抽出
  - iloc を使った抽出
  - [条件式] を使った選択

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# あやめのデータセットを読み込み(CSV)


# [列名] を使って、Speciesカラムの先頭5行を表示

Id
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
Name: Species, dtype: str

In [ ]:
# .列名 を使って、Speciesカラムの先頭5行を表示

Id
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
Name: Species, dtype: str

In [ ]:
# [[列名]] を使って、PetalLengthCmとPetalWidthCm、Speciesを表示

     PetalLengthCm  PetalWidthCm         Species
Id
1              1.4           0.2     Iris-setosa
2              1.4           0.2     Iris-setosa
3              1.3           0.2     Iris-setosa
4              1.5           0.2     Iris-setosa
5              1.4           0.2     Iris-setosa
..             ...           ...             ...
146            5.2           2.3  Iris-virginica
147            5.0           1.9  Iris-virginica
148            5.2           2.0  Iris-virginica
149            5.4           2.3  Iris-virginica
150            5.1           1.8  Iris-virginica

[150 rows x 3 columns]

In [ ]:
# loc[行,列] を使って、データの範囲・位置を指定して複数の値を抽出

    PetalLengthCm  PetalWidthCm      Species
Id
1             1.4           0.2  Iris-setosa
2             1.4           0.2  Iris-setosa
3             1.3           0.2  Iris-setosa
4             1.5           0.2  Iris-setosa
5             1.4           0.2  Iris-setosa

In [ ]:
# iloc[行番号,列番号] を使って、データの範囲・位置を番号で指定して複数の値を抽出

    PetalLengthCm  PetalWidthCm      Species
Id
1             1.4           0.2  Iris-setosa
2             1.4           0.2  Iris-setosa
3             1.3           0.2  Iris-setosa
4             1.5           0.2  Iris-setosa
5             1.4           0.2  Iris-setosa

In [ ]:
# 条件抽出: Speciesカラムの値が"Iris-virginica"の行を抽出して先頭5行を表示

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
101            6.3           3.3            6.0           2.5  Iris-virginica
102            5.8           2.7            5.1           1.9  Iris-virginica
103            7.1           3.0            5.9           2.1  Iris-virginica
104            6.3           2.9            5.6           1.8  Iris-virginica
105            6.5           3.0            5.8           2.2  Iris-virginica

In [ ]:
#@title 送信処理用共通プログラム（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown 解答の送信に必要です。（中身は絶対に修正しないでください）

import os
os.makedirs(".client/python", exist_ok=True)  # 隠しフォルダを作成
!wget -q https://raw.githubusercontent.com/YasuharuSuzuki/26_programing2/main/91_notebook_client/src/setup.sh -O .client/setup.sh   # 外部コードをダウンロードして隠しフォルダに配置
!chmod +x ./.client/setup.sh
!bash ./.client/setup.sh # 実行

# モジュールの初期化
exec(open('.client/client_setup.py').read())

# ノートブック固有の設定
NOTEBOOK_PATH = "12_pandas/02_データの抽出と統計操作.ipynb"
set_notebook_config(NOTEBOOK_PATH)

In [ ]:
#@title 問4 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=4, button_name="練習プログラム"))

---
---
---
---
---

## 📋 サンプルプログラム5　統計
- min() / max() / sum() / mean() / median() / var() / std() / quantile()
- unique() / value_counts()
- describe()

### min() / max() / sum() / mean() / median() / var() / std() / quantile() を使った各種統計量の算出
- min() --- 最小値
- max() --- 最大値
- sum() --- 合計値
- mean() --- 平均値
- median() --- 中央値
- var() --- 分散
- std() --- 標準偏差
- [quantile()](https://note.nkmk.me/python-pandas-quantile/) --- 分位数

In [15]:
# 最小値
df_wine.alcohol.min()

np.float64(11.03)

In [16]:
# 最大値
df_wine.alcohol.max()

np.float64(14.83)

In [17]:
# 合計値
df_wine.alcohol.sum()

np.float64(2314.11)

In [18]:
# 平均値
df_wine.alcohol.mean()

np.float64(13.00061797752809)

In [19]:
# 中央値
df_wine.alcohol.median()

np.float64(13.05)

In [20]:
# 分散
df_wine.alcohol.var()

np.float64(0.6590623278105759)

In [21]:
# 標準偏差
df_wine.alcohol.std()

np.float64(0.8118265380058575)

In [22]:
# 分位数
df_wine.alcohol.quantile(0.25)  # 25% タイルを取得

np.float64(12.362499999999999)

### ユニークな要素の抽出と、出現頻度の算出
- ユニークとは？
  - ユニークとはデータや識別名などについて、他と重複のない（重複を取り除いた）データのこと。
  - 「ユニークなデータ」「一意なデータ」とも言います。
- ユニークを扱うメソッド
  - unique()を使用するとユニークな要素を抽出します。
  - [value_counts()](https://note.nkmk.me/python-pandas-value-counts/) を使うと、ユニークな要素の抽出と、各要素の出現回数を算出できます。

In [23]:
# unique() ユニークな要素の抽出
df_wine.target.unique()

array([1, 2, 3])

- target(ワインの品種)は３種類ある

In [24]:
# value_counts() ユニークな要素の抽出と出現頻度の算出
df_wine.target.value_counts()

target
2    71
1    59
3    48
Name: count, dtype: int64

- target(ワインの品種)では、品種2がややデータ量が多い

### 要約統計量の取得
- [describe()](https://note.nkmk.me/python-pandas-describe/) を使うと、各列の平均、中央値、最小値などの要約統計量が取得できます。

In [25]:
# describe() 要約統計量の算出
df_wine.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,1.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,1.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,1.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,2.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,3.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,3.000000

## ⚖️ 練習プログラム5　統計 (25点)
- あやめのデータセットについて各種統計を行ってみましょう
  - min() / max() / sum() / mean() / median() / var() / std() / quantile() を使って各種統計値を算出してみましょう。
  - unique() / value_counts() でユニークな要素の抽出と、出現頻度を算出してみましょう。
  - describe() で各列の要約統計量を取得してみましょう。

<!-- PROBLEM_TYPE: SYNTAX_EXERCISE -->

In [ ]:
# 最小値

np.float64(4.3)

In [ ]:
# 最大値

np.float64(7.9)

In [ ]:
# 合計値

np.float64(876.5)

In [ ]:
# 平均値

np.float64(5.843333333333334)

In [ ]:
# 中央値

np.float64(5.8)

In [ ]:
# 分散

np.float64(0.6856935123042507)

In [ ]:
# 標準偏差

np.float64(0.828066127977863)

In [ ]:
# 分位数

np.float64(6.4)

In [ ]:
# unique() ユニークな要素の抽出

<StringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str

In [ ]:
# value_counts() ユニークな要素の抽出と出現頻度の算出

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
# describe() 要約統計量の算出

       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count     150.000000    150.000000     150.000000    150.000000
mean        5.843333      3.054000       3.758667      1.198667
std         0.828066      0.433594       1.764420      0.763161
min         4.300000      2.000000       1.000000      0.100000
25%         5.100000      2.800000       1.600000      0.300000
50%         5.800000      3.000000       4.350000      1.300000
75%         6.400000      3.300000       5.100000      1.800000
max         7.900000      4.400000       6.900000      2.500000

In [ ]:
#@title 問5 送信ボタン表示（以下のセルを「▶ 実行」して下さい。） { display-mode: "form" }
#@markdown メールアドレスを取得して、送信ボタンを押してください（中のプログラムは絶対に修正しないでください）
display(create_submit_button(problem_number=5, button_name="練習プログラム"))